import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chug Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header></Header>
        {children}
      </body>
      {/* ADD FOOTER HERE */}
    </html>
  );
}
